projectName: my-example

targets:
  - name: infra-example
    build:
      plugin: builtin/DockerBuild
      path: samples/examples/infra/Dockerfile
      include:
        - samples/examples/infra/**
    deploy:
      plugin: builtin/DockerRun
      secrets:
        - key: GH_ADMIN_TOKEN
          envValue: GITHUB_TOKEN
          loadFromFile: true

  - name: example-api
    build:
      plugin: builtin/DockerBuild
      path: samples/examples/api/Dockerfile
      include:
        - samples/examples/api/**
    deploy:
      plugin: builtin/K8sDeploy
      runtimeConfiguration: samples/examples/ui/k8s.yaml

  - name: test-example
    build:
      plugin: builtin/DockerBuild
      path: samples/examples/tests/Dockerfile
      include:
        - samples/examples/tests/**
    deploy:
      plugin: builtin/DockerRun
      runFromK8s: true
