build:
  stages:
  - plugin: builtin/DockerBuild
    params:
      name: infra-example
      path: samples/examples/infra/Dockerfile
      include:
        - samples/examples/infra/**

  - plugin: builtin/DockerBuild
    params:
      name: example-api
      path: samples/examples/api/Dockerfile
      include:
        - samples/examples/api/**

  - plugin: builtin/DockerBuild
    params:
      name: test-example
      path: samples/examples/tests/Dockerfile
      include:
        - samples/examples/tests/**

deploy:

  stages:
  - name: deploy-infra
    plugin: builtin/DockerRun
    params:
      skipenvironments:
        - localk8s
      targets:
        - name: infra-example
          secrets:
            - key: GH_ADMIN_TOKEN
              envValue: GITHUB_TOKEN
            - key: SPN_PASS
              envValue: SPN_PASSWORD

  - name: k8s-deploy
    plugin: builtin/HelmDeploy
    params:
      release: 'my-cool-thing'
      targets:
        - name: example-ui
        - name: example-consumer
        - name: example-api
          secrets:
            - key: SQL_CONNECTION_STRING
              envValue: DB_CONNECTION


  - name: run-tests
    plugin: builtin/K8sRun
    params:
      targets:
        - name: test-example
          secrets:
            - key: TEST_USER_PASSWORD
              envValue: TEST_USER_PASSWORD
