build:
  stages:
  - name: infra-example
    plugin: builtin/DockerBuild
    params:
      path: samples/examples/infra/Dockerfile
      include:
        - samples/examples/infra/**

  - name: example-api
    plugin: builtin/DockerBuild
    params:
      path: samples/examples/api/Dockerfile
      include:
        - samples/examples/api/**

  - name: test-example
    plugin: builtin/DockerBuild
    params:
      path: samples/examples/tests/Dockerfile
      include:
        - samples/examples/tests/**

deploy:

  secretloader:
    plugin: builtin/AWSLoader
    # TODO - secret loader would need to know what the convention was for getting secrets from cloud services based on the project name

  stages:
  - name: deploy-infra
    plugin: builtin/DockerRun
    params:
      targets:
        - name: infra-example
          secrets:
            - key: GH_ADMIN_TOKEN
              envValue: GITHUB_TOKEN

  - name: k8s-deploy
    plugin: builtin/HelmDeploy
    # git checkout github.com/company/cloud-platform@v1
    # cd shared/helm
    # helm install --upgrade -f /build-arfefacts/manifest.yaml -f /build-arfefacts/secrets.yaml -f samples/examples/api/k8s.yaml
    #    --namespace "my-cool-thing-feature/abc"
    #    --release "my-cool-thing" .

    params:
      chart: github.com/company/cloud-platform/shared/helm@v1
      release: 'my-cool-thing'
      namespaceprefix: 'my-cool-thing'
      featurebranchnamespacing: true
      targets:
        - name: example-api
          helmvalues: samples/examples/api/k8s.yaml # optional
          secrets:
            - key: SQL_CONNECTION_STRING
              envValue: DB_CONNECTION

        - name: example-ui

  - name: run-tests
    plugin: builtin/K8sRun
    params:
      targets:
        - name: test-example
          secrets:
            - key: TEST_USER_PASSWORD
              envValue: TEST_USER_PASSWORD
